#! /bin/bash

../myhttpd 0 > /dev/null 2>&1 &
PID=$!

# Randomize last modified times
for FILE in ./http-root-dir/htdocs/directory/; do
  touch -m -t $(date -d @$(shuf -i "0-$(date +%s)" -n 1) +%Y%m%d%H%M.%S) "$FILE"
done
sleep 1
#PORT=$(ss -l -p -n | grep $PID | awk '{print $5}' | cut -d ":" -f2)
PORT=$(netstat -ntlp 2> /dev/null | awk 'split($7, a, "/"); split($4, b, ":"); {print b[2]" "a[1]}' | awk -v pid="$PID" '$2==pid {print $1}')
USERSTRING=$(cat ../auth.txt)
L_DIR_LISTINGS=( "$(LC_COLLATE=C ls -1 ./http-root-dir/htdocs/directory/)" "$(LC_COLLATE=C ls -1r ./http-root-dir/htdocs/directory/)" "$(ls -t ./http-root-dir/htdocs/directory/)" "$(ls -tr ./http-root-dir/htdocs/directory/)" "$(ls -S ./http-root-dir/htdocs/directory/)" "$(ls -Sr ./http-root-dir/htdocs/directory/)")

for S_ORDER in {0..5}; do
  R_DIR_LISTING=$(python3 sortsearch.py $S_ORDER $PORT)
  L_DIR_LISTING=${L_DIR_LISTINGS[$S_ORDER]}
  diff -wq <(printf "$R_DIR_LISTING") <(printf "$L_DIR_LISTING") > /dev/null 2>&1
  if [[ $? != 0 ]]; then
    printf "\033[0;31m$(basename "$0")  Failed.\033[0m\n"
    kill -15 $PID
    exit 1
  fi
done
printf "\033[0;32m$(basename "$0")  Passed.\033[0m\n"
kill -15 $PID
exit 0
