#! /bin/bash

#! /bin/bash

# Start Server
../myhttpsd 0 > /dev/null 2>&1 &
PID=$!

# Set Limits
prlimit --nproc=50 --cpu=600 --rss=4000000 -p $PID

sleep 1
PORT=$(ss -l -p -n | grep $PID | awk '{print $5}' | cut -d ":" -f2)
USERSTRING=$(cat ../auth.txt)
CODE=$(echo "GET / HTPC/1.1\nHost: 127.0.0.1:$PORT\nAuthorization: Basic $(cat ../auth.txt)" | nc -w 3 127.0.0.1 $PORT | head -n 1 | cut -d " " -f2)
kill -15 $PID
if [[ $CODE != 400 ]]; then
  printf "\033[0;31m$(basename "$0") Failed.\033[0m\n"
  exit 1
else
  printf "\033[0;32m$(basename "$0") Passed.\033[0m\n"
  exit 0
fi
