#! /bin/bash

../myhttpd -t 0 > /dev/null 2>&1 &
PID=$!

prlimit --nproc=50 --cpu=600 --rss=4000000 -p $PID

#PORT=$(ss -l -p -n | grep $PID | awk '{print $5}' | cut -d ":" -f2)
PORT=$(netstat -ntlp 2> /dev/null | awk 'split($7, a, "/"); split($4, b, ":"); {print b[2]" "a[1]}' | awk -v pid="$PID" '$2==pid {print $1}')
USERSTRING=$(cat ../auth.txt)
sleep 1
for i in {0..32}; do
  nc -q -1 127.0.0.1 $PORT &
  P=$!
  disown $!
  PIDS="$PIDS $P"
done
for P in $PIDS; do
  kill -9 $P
done
NCPID=$!
CODE=$(curl --max-time 3 -s -u $USERSTRING "127.0.0.1:$PORT/simple.html")
CODEA=$?
if kill -0 $PID 2> /dev/null; then
  if [[ $CODEA == 0 ]]; then
    printf "\033[0;32m$(basename "$0") Passed.\033[0m\n"
    kill -15 $PID
    exit 0
  fi
fi
printf "\033[0;31m$(basename "$0") Failed.\033[0m\n"
kill -15 $PID
exit 1
