#! /bin/bash

../myhttpsd 0 > /dev/null 2>&1 &
PID=$!

# Set limits
prlimit --nproc=50 --cpu=600 --rss=4000000 -p $PID

sleep 1
PORT=$(ss -l -p -n | grep $PID | awk '{print $5}' | cut -d ":" -f2)
USERSTRING=$(base64 < ../auth.txt)
CODE=$(printf "GET / HTTP/2\r\nAuthorization: Basic %s\r\nAccept: */*\r\n\r\n" "$USERSTRING" | nc 127.0.0.1 $PORT | head -n 1 | cut -d " " -f2)
kill -15 $PID
if [[ $CODE != 505 ]]; then
  printf "\033[0;31m$(basename "$0") Failed.\033[0m\n"
  exit 1
else
  printf "\033[0;32m$(basename "$0") Passed.\033[0m\n"
  exit 0
fi
