#! /bin/bash

../myhttpsd 0 > /dev/null 2>&1 &
PID=$!
chmod +x ./http-root-dir/cgi-bin/*
sleep 1
#PORT=$(ss -l -p -n | grep $PID | awk '{print $5}' | cut -d ":" -f2)
PORT=$(netstat -ntlp 2> /dev/null | awk 'split($7, a, "/"); split($4, b, ":"); {print b[2]" "a[1]}' | awk -v pid="$PID" '$2==pid {print $1}')
USERSTRING=$(cat ../auth.txt)
diff -wq <(curl -k -s -u $USERSTRING "https://127.0.0.1:$PORT/cgi-bin/date" | head -n +2) <(date)
CODE=$?
kill -15 $PID
if [[ $CODE != 0 ]]; then
  printf "\033[0;31m$(basename "$0") Failed.\033[0m\n"
  exit 1
else
  printf "\033[0;32m$(basename "$0") Passed.\033[0m\n"
  exit 0
fi
