#!/bin/bash

if (( $# != 1 ))
then
  echo "Usage: verify <filename>"
  exit 1
fi

if ! [[ -r $1 ]]
then
  echo "Error: "$1" is not readable!"
  exit 1
fi

linenum=0

while read
do
  line=$REPLY # $REPLY preserves whitespace
  (( linenum++ ))
  valid_bday=0
  valid_name=0

  bday=$(echo $line | cut -d '-' -f 1)
  name=$(echo $line | cut -d '-' -f 2)
  
  # BIRTHDAY CHECK

  number_regex="^[0-9]+$"
  bday_m=$(echo $bday | cut -d '/' -f 1)
  if [[ $bday_m =~ $number_regex ]]
  then
    bday_m=$((10#$bday_m))
  fi
  bday_d=$(echo $bday | cut -d '/' -f 2)
  if [[ $bday_d =~ $number_regex ]]
  then
    bday_d=$((10#$bday_d))
  fi
  bday_y=$(echo $bday | cut -d '/' -f 3)
  if [[ $bday_y =~ $number_regex ]]
  then
    bday_y=$((10#$bday_y))
  fi
  bday_y_prefix=${bday_y:0:2}
  if [[ $bday_y_prefix =~ $number_regex ]]
  then
    bday_y_prefix=$((10#$bday_y_prefix))
  fi
  bday_y_suffix=${bday_y:2:2}
  if [[ $bday_y_suffix =~ $number_regex ]]
  then
    bday_y_suffix=$((10#$bday_y_suffix))
  fi
  bday_m_len=$(echo $bday_m | wc -c)
  (( bday_m_len -= 1 ))
  bday_d_len=$(echo $bday_d | wc -c)
  (( bday_d_len -= 1 ))
  bday_y_len=$(echo $bday_y | wc -c)
  (( bday_y_len -= 1 ))
  #echo bday_y_len = $bday_y_len

  if (( $bday_y_len != 2 && $bday_y_len != 4 ))
  then
    valid_bday=1
    #echo bday_y_len not valid!
  fi

  if (( $bday_m < 1 || $bday_m > 12 ))
  then
    valid_bday=1
    #echo bday_month is out of range!
  fi

  if (( $bday_d < 1 || $bday_d > 31 ))
  then
    valid_bday=1
    #echo bday_day is out of range!
  fi

  if (( $bday_y_len == 4 ))
  then
    if (( $bday_y_prefix != 19 && $bday_y_prefix != 20 ))
    then
      valid_bday=1
      #echo bday_y_prefix is out of range!
    fi
  fi

  # NAME CHECK

  first_name=$(echo $name | cut -d ',' -f 1)
  last_name=$(echo $name | cut -d ',' -f 2 | cut -d ' ' -f 2)
  middle_initial=$(echo $name | cut -d ',' -f 2 | cut -d ' ' -f 3)

  if ! [[ $first_name =~ ^[A-Z][a-z]+$ ]]
  then
    valid_name=1
    #echo first_name not good
  fi
  
  if [[ $line =~ [[:space:]+]$ ]]
  then
    valid_name=1
    #echo trailing space
  fi

  if ! [[ -z "$middle_initial" ]]
  then
    if ! [[ $middle_initial =~ ^[A-Z].$ ]]
    then
      valid_name=1
      #echo middle_initial not good
    fi
    if ! [[ $last_name =~ [A-Z][a-z]+ ]]
    then
      valid_name=1
      #echo last_name not good with middle initial
    fi
  else
    #echo middle initial does not exist
    if ! [[ $last_name =~ ^[A-Z][a-z]+$ ]]
    then
      valid_name=1
      #echo last_name not good in this other place idk
    fi
  fi

  if [[ "$valid_name" == 1 && "$valid_bday" == 1 ]]
  then
    echo "Line "$linenum" has an invalid name and birth date."
    continue
  fi

  if [[ "$valid_bday" == 1 ]]
  then
    echo "Line "$linenum" has an invalid birth date."
    continue
  fi

  if [[ "$valid_name" == 1 ]]
  then
    echo "Line "$linenum" has an invalid name."
    continue
  fi

  if [[ "$valid_name" == 0 && "$valid_bday" == 0 ]]
  then
    echo "Line "$linenum" is valid."
    continue
  fi

done < $1
