#! /bin/bash

rm -rf out.txt

N=20

./part1 $N $N > out.txt

consumed=`cat out.txt | grep consumed`
produced=`cat out.txt | grep produced`

for ((i=1;i<$N;i++)); do
    #echo $i
    consume_count=`cat out.txt | grep " $i consumed" | wc -l`
    #echo $consume_count
    produce_count=`cat out.txt | grep " $i produced" | wc -l`
    
    if [[ ${produce_count} -ne 33 ]]; then
        echo -e "Thread ${i} produced ${produce_count} != 33"
        echo -e "\e[31mtest_part1_count failed.\033[0m"
        exit 1
    elif [[ ${consume_count} -ne 33 ]]; then
        echo -e "Thread ${i} consumed ${consume_count} != 33"
        echo -e "\e[31mtest_part1_count failed.\033[0m"
        exit 1
    fi
done

rm -rf out.txt

echo -e "\e[32mtest_part1_count passed!\033[0m"


